security:
    # Hashers de mot de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseurs de sécurité
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    # Configuration des pare-feux
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator:
                - App\Security\SecurityAuthenticator
                - App\Security\GoogleAuthenticator
            logout:
                path: app_logout
                target: /

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # always_remember_me: true

    # Contrôle d'accès
    access_control:
        - { path: ^/admin, roles: ROLE_EXPERT }
        - { path: ^/senior, roles: ROLE_SENIOR }
        - { path: ^/apprenti, roles: ROLE_APPRENTI }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
