controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
redirection_vue:
    path: /redirection
    controller: App\Controller\HomeController::index

    # config/routes.yaml pour générer pdf et envoi par mail
app_generate_pdf_and_send_email:
    path: '/generate-pdf-and-send-email/{id}'
    controller: 'App\Controller\MailController::generatePdfAndSendEmail'

connect_google_start:
    path: /oauth/connect/google
    controller: App\Controller\SocialOAuthController::authLogin

connect_google_check:
    path: /oauth/check/google
    controller: App\Controller\SocialOAuthController::check

