controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
redirection_vue:
    path: /redirection
    controller: App\Controller\HomeController::index